spring:
  application:
    name: shoppe

  datasource:
    url: jdbc:mysql://localhost:3306/shopee_clone
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true     # log SQL
    properties:
      hibernate:
        format_sql: true

server:
  port: 8000
jwt:
  secret: ZmFrZV9kZWZhdWx0X3NlY3JldF9mb3Jfc2hvcHBlZmFrZV9kZWZhdWx0X3NlY3JldF9mb3Jfc2hvcHBl
  expiration: 3600000 # 1 hour in milliseconds
